name: CI

on:
  push:
    branches:
      - main

  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby 3.0.1
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.0.1

    - name: Run Rubocop
      run: make lint  

    - name: Run tests
      run: make test
